[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[context.deploy-preview]
		command = "npm run build && sed -i s/API_KEY_PLACEHOLDER/$COMMIT_REF/g netlify.toml && npm run lh https://deploy-preview-155--gatsby-netlify-cms.netlify.com/"
[context.deploy-preview.environment]
    TRAVIS_PULL_REQUEST = "155"
    TRAVIS_PULL_REQUEST_SHA = "COMMIT_REF"
    TRAVIS_PULL_REQUEST_SLUG = "netlify-templates/gatsby-starter-netlify-cms"
    TRAVIS_EVENT_TYPE = "pull_request"

    
