[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[context.deploy-preview]
		build = "npm run lh https://gatsby-netlify-cms.netlify.com"
